### PR TITLE
Simplify help.js and add an error handler

### PR DESCRIPTION
**Pull request by QkeleQ10**
I've rebuilt some systems in help.js. I haven't had the chance to test it, so I hope you can test this. Keep in mind that this commit needs to stay revertable, in case something goes wrong! Please keep me updated on how it goes.

### CODE REVIEW

**Comment by QkeleQ10** [comment]
You might also want to implement CI checks to this repo, like we had on the old repository.

**Comment by QkeleQ10** [comment]
~~it'll probably not work lol show me any error logs and I'll fix them~~

**Comment by ImRodry** [comment]
I’ll test this later but please add back the usage and cooldown.

**Comment by QkeleQ10** [comment]
What do you mean?

**Comment by ImRodry** [comment]
I changed the usage and added a 60 second cooldown which you removed for some reason (the cooldown was due to the collectors)

**Comment by QkeleQ10** [comment]
Will add those back 👍 I didn't remove that, I made the changes yesterday before you did 😉

**Pull request merged**
